
server:
  port: 9093

spring:
  application:
    name: MSA-Cafe-Hystrix-Dashboard

  #Config Server
  cloud:
    config:
      uri: http://localhost:8888
      name: MSA-Cafe-Config-Server

#Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/